// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlantandBiologyRecognition.DAL.Models;

public partial class RefreshToken
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public DateTime? CreateAt { get; set; }

    public DateTime? ExpiresAt { get; set; }

    public string Token { get; set; }

    public virtual User User { get; set; }
}