// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlantandBiologyRecognition.DAL.Models;

public partial class Sample
{
    public Guid SampleId { get; set; }

    public string Name { get; set; }

    public string ScientificName { get; set; }

    public Guid? CategoryId { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<Learningtip> Learningtips { get; set; } = new List<Learningtip>();

    public virtual ICollection<Recognitionhistory> Recognitionhistories { get; set; } = new List<Recognitionhistory>();

    public virtual ICollection<Sampledetail> Sampledetails { get; set; } = new List<Sampledetail>();

    public virtual ICollection<Sampleimage> Sampleimages { get; set; } = new List<Sampleimage>();

    public virtual ICollection<Savedsample> Savedsamples { get; set; } = new List<Savedsample>();

    public virtual ICollection<Textbooklink> Textbooklinks { get; set; } = new List<Textbooklink>();
}