// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlantandBiologyRecognition.DAL.Models;

public partial class Textbooklink
{
    public Guid LinkId { get; set; }

    public Guid? SampleId { get; set; }

    public string TextbookName { get; set; }

    public int? Chapter { get; set; }

    public string Lesson { get; set; }

    public virtual Sample Sample { get; set; }
}