// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlantandBiologyRecognition.DAL.Models;

public partial class Account
{
    public Guid Accountid { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Roleid { get; set; }

    public bool? Isactive { get; set; }

    public virtual ICollection<Educationmaterial> Educationmaterials { get; set; } = new List<Educationmaterial>();

    public virtual ICollection<History> Histories { get; set; } = new List<History>();

    public virtual ICollection<Speciman> Specimen { get; set; } = new List<Speciman>();
}