// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlantandBiologyRecognition.DAL.Models;

public partial class Educationmaterial
{
    public Guid Materialid { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Filepath { get; set; }

    public DateTime? Createdat { get; set; }

    public DateTime? Updateat { get; set; }

    public Guid? Createby { get; set; }

    public virtual Account CreatebyNavigation { get; set; }

    public virtual ICollection<Speciman> Specimen { get; set; } = new List<Speciman>();
}