// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlantandBiologyRecognition.DAL.Models;

public partial class History
{
    public Guid Sessionid { get; set; }

    public Guid? Userid { get; set; }

    public DateTime? Createdat { get; set; }

    public string Aimodel { get; set; }

    public string Imageuri { get; set; }

    public string Answer { get; set; }

    public Guid? Specimen { get; set; }

    public virtual Speciman SpecimenNavigation { get; set; }

    public virtual Account User { get; set; }
}