// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlantandBiologyRecognition.DAL.Models;

public partial class Learningtip
{
    public int TipId { get; set; }

    public int? SampleId { get; set; }

    public string TipText { get; set; }

    public virtual Sample Sample { get; set; }
}