// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlantandBiologyRecognition.DAL.Models;

public partial class Sampledetail
{
    public int DetailId { get; set; }

    public int? SampleId { get; set; }

    public string Description { get; set; }

    public string Habitat { get; set; }

    public string Behavior { get; set; }

    public string OtherInfo { get; set; }

    public virtual Sample Sample { get; set; }
}