// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlantandBiologyRecognition.DAL.Models;

public partial class Sampleimage
{
    public int ImageId { get; set; }

    public int? SampleId { get; set; }

    public string ImageUrl { get; set; }

    public string Description { get; set; }

    public virtual Sample Sample { get; set; }
}