// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlantandBiologyRecognition.DAL.Models;

public partial class Savedsample
{
    public Guid SavedId { get; set; }

    public Guid? UserId { get; set; }

    public Guid? SampleId { get; set; }

    public DateTime? SavedAt { get; set; }

    public virtual Sample Sample { get; set; }

    public virtual User User { get; set; }
}