// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlantandBiologyRecognition.DAL.Models;

public partial class Textbooklink
{
    public int LinkId { get; set; }

    public int? SampleId { get; set; }

    public string TextbookName { get; set; }

    public int? PageNumber { get; set; }

    public string ContentSummary { get; set; }

    public virtual Sample Sample { get; set; }
}