// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlantandBiologyRecognition.DAL.Models;

public partial class Userrole
{
    public Guid RoleId { get; set; }

    public string RoleName { get; set; }

    public Guid UserId { get; set; }

    public virtual User User { get; set; }
}